[package]
name = "arb-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "1.14.12"
spl-associated-token-account = "1.1.3"
spl-token = "3.5.0"
